export const ADD_ONE = "ADD_ONE";

export const UPGRADE_STORAGE = "UPGRADE_STORAGE";

export const OPEN_NOTIFICATION = "OPEN_NOTIFICATION";

export const CLOSE_NOTIFICATION = "CLOSE_NOTIFICATION";

export const PUSH_NOTIFICATION_TO_LIST = "PUSH_NOTIFICATION_TO_LIST";

export const CLEAR_NOTIFICATIONS_LIST = "CLEAR_NOTIFICATIONS_LIST";